// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiffDetail(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectLeftFile():Promise<string>;

export function SelectRightFile():Promise<string>;

export function StartCompare(arg1:string,arg2:string):Promise<void>;
