// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDiffDetail(arg1:string,arg2:string):Promise<main.DiffDetailResult>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function StartCompare(arg1:string,arg2:string):Promise<void>;
