// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiffDetail(arg1, arg2) {
  return window['go']['main']['App']['GetDiffDetail'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartCompare(arg1, arg2) {
  return window['go']['main']['App']['StartCompare'](arg1, arg2);
}
